const obj = {
    "Araçlar & Materyaller:": "Tools & Materials:",
    "Aşama 1 — Hazırlık & Başlangıç:": "Stage 1 — Prep & Start:",
    "Aşama 2 — Asıl İş & İpuçları:": "Stage 2 — Main Work & Tips:",
    "Aşama 3 — Sonuç & Dersler:": "Stage 3 — Results & Lessons:",
    "Başlangıç Hedefi:": "Initial Goal:",
    "Throwing Rocks — Zorluklar:": "Throwing Rocks — Challenges:",
    "Sürecin Öğrettikleri:": "Lessons Learned:",
    "Kitaplar & Makaleler:": "Books & Articles:",
    "Videolar & Podcastler:": "Videos & Podcasts:",
    "Açık Düğümler — Takip Et:": "Open Nodes — Follow:",
    "Eskiden (Yanlış İnançlar):": "In the Past (False Beliefs):",
    "Şu An (Dönüşüm):": "Now (Transformation):",
    "Merak Kabinesi": "Cabinet of Curiosities",
    "Her eser bir müze objesidir. Kategorilere tıkla, serüvenin galerisini gör. Favori fikirlerini yıldızla.": "Every work is a museum object. Click on categories, see the gallery of your adventure. Star your favorite ideas.",
    "Etiketler:": "Tags:",
    "Temizle": "Clear",
    "STOCK CONSOLIDATION": "STOCK CONSOLIDATION",
    "— 10 esere ulaştın! Austin Kleon der ki: \"Kendi sesini bulmanın yolu, başkalarının seslerini birleştirmekten geçer.\" Hemen bir rehber oluştur.": "— Reached 10 works! Austin Kleon says: \"The way to find your own voice is to mix the voices of others.\" Create a guide now.",
    "Şablon Seç veya Sihirbazı Başlat": "Select Template or Start Wizard",
    "Sihirbazla Devam Et": "Continue with Wizard",
    "Sihirbazı Başlat": "Start Wizard",
    "Kabineye Dön": "Return to Cabinet",
    "Taslak": "Draft",
    "Yayınlanmış": "Published",
    "Tüm Eserleri Sil": "Delete All Works",
    "Burada hiç fikir yok.": "There are no ideas here.",
    "Bu kategoride henüz bir müze objesi yok.": "There is no museum object in this category yet.",
    "Kayıp eserler aranıyor...": "Searching for lost works...",
    "KAPAT": "CLOSE",
    "Hemingway Taktiği": "Hemingway Tactic",
    "Bu taslak yarım kalmış. Kaldığın yerden devam etmek için aşağıdaki butona bas — fikir Akış'a yüklenecek.": "This draft is incomplete. Press the button below to continue where you left off — the idea will be loaded to Flow.",
    "Bugün Devam Et": "Continue Today",
    "MÜZE ESERLERİ": "MUSEUM WORKS",
    "Görüntüle": "View",
    "ATIF — İLHAM KAYNAĞI": "ATTRIBUTION — INSPIRATION",
    "Yeniden Ziyaret Notu": "Revisit Note",
    "Yayınla": "Publish",
    "Dolduracağın Alanlar": "Fields to Fill",
    "Başla — Soruları Cevapla": "Start — Answer Questions",
    "Vazgeç": "Cancel",
    "Her soruyu dürüstçe cevapla. Mükemmel olmasına gerek yok.": "Answer every question honestly. It doesn't have to be perfect.",
    "Önizle →": "Preview →",
    "← Geri": "← Back",
    "Rehber Önizleme": "Guide Preview",
    "\"İyi bir fikir asla tam bitmez, sadece yayınlanır.\" — Austin Kleon": "“A good idea is never completely finished, it just gets published.” — Austin Kleon",
    "Yayınla ✓": "Publish ✓",
    "← Düzelt": "← Edit",
    "Stok Tamamlandı!": "Stock Completed!",
    "etiketindeki eserlerini kalıcı bir değere dönüştürdün.": "you transformed your works in the tag into a permanent value.",
    "\"Küçük şeyler zamanla büyür. Bu rehber, birinin öğrenme yolculuğundaki bir kavşak noktası olacak.\" — Austin Kleon": "“Small things grow over time. This guide will be a crossroads in someone’s learning journey.” — Austin Kleon",
    "Stock Consolidation": "Stock Consolidation",
    "ADIM 0 — Zaman Çizgisi + Seçim": "STEP 0 — Timeline + Selection",
    "Birleştirmek istediğin fikirleri seç. Kleon felsefesi: \"Noktaları birleştir, bütünü gör.\"": "Select the ideas you want to combine. Kleon philosophy: \"Connect the dots, see the whole.\"",
    "ADIM 1 — ÖRÜNTÜ BULUNDU": "STEP 1 — PATTERN FOUND",
    "Aşağıdaki kelimeler seçtiğin fikirlerde en çok geçen örüntülerdir. Rehberinde vurgulamak istediklerini onayla.": "The following words are the most common patterns in the ideas you selected. Confirm what you want to emphasize in your guide.",
    "SİSTEM ÖNERİSİ": "SYSTEM RECOMMENDATION",
    "Bu fikirler ve onayladığın kelimeler en çok şu şablona uyuyor:": "These ideas and the words you confirmed fit this template best:",
    "Kleon der ki: \"Rehberin yapısı içindeki örüntüye göre şekillenir.\"": "Kleon says: \"The structure of the guide takes shape according to the pattern inside it.\"",
    "Onayladıklarımla Devam Et →": "Continue with My Selections →",
    "ADIM 2 — Şablonu Kesinleştir": "STEP 2 — Finalize Template",
    "Önerilen şablon en uygunu gibi görünüyor, ancak istersen başka bir tane seçebilirsin.": "The recommended template seems to be the most suitable, but you can choose another one if you want.",
    "ÖNERİLEN": "RECOMMENDED",
    "Seçili Şablonla Yazmaya Başla →": "Start Writing with Selected Template →",
    "ADIM 3 — Rehberi Oluştur": "STEP 3 — Create Guide",
    "Fikirlerini birleştirerek yeni bir değer üret. Yan taraftaki referansları kullanarak hızlanabilirsin.": "Create a new value by combining your ideas. You can speed up by using the references on the side.",
    "Seçtiğin fikirlerden:": "From your selected ideas:",
    "Önizleme ve Yayınla →": "Preview and Publish →",
    "ADIM 4 — SON DOKUNUŞLAR": "STEP 4 — FINAL TOUCHES",
    "Tamamlanmış Rehberin": "Your Completed Guide",
    "← Düzenle": "← Edit",
    "Muazzam Stok Eritme!": "Massive Stock Clearing!",
    "Seçtiğin fikirleri birleştirerek": "By combining the ideas you selected",
    "üzerine harika bir rehber oluşturdun. Austin Kleon gurur duyardı!": "you created a great guide on it. Austin Kleon would be proud!",
    "Araçlar & Malzemeler": "Tools & Materials",
    "Aşama 1: Hazırlık": "Stage 1: Prep",
    "Aşama 2: Uygulama": "Stage 2: Execution",
    "Sonuç Tablosu": "Results Table",
    "Hedef": "Goal",
    "Karşılaştığım Zorluklar": "Challenges I Faced",
    "Çıkardığım Dersler": "Lessons I Learned",
    "Okuma Kaynakları": "Reading Sources",
    "Ses ve Video": "Audio and Video",
    "Sahiplenilecek Kişiler": "People to Own",
    "Eskiden Böyle Düşünürdüm": "I Used to Think So",
    "Artık Şunu Biliyorum": "Now I Know This",
    "Uzman değilim, deneme yanılma yapıyorum.": "I'm not an expert, I'm doing trial and error.",
    "HEMINGWAY TAKTİĞİ": "HEMINGWAY TACTIC",
    "Fikir Defteri": "Idea Notebook",
    "Örüntü (Pattern) Bulma": "Finding Pattern",
    "Kleon der ki: \"Bu içeriklere yukarıdan bak. Ortak nokta ne? Aynı dili mi kullanıyorlar, aynı hatayı mı çözüyorlar?\"": "Kleon says: \"Look at these contents from above. What is the common point? Are they using the same language, solving the same mistake?\"",
    "Görev:": "Task:",
    "Bu rehberin ana fikrini, örüntüyü hissettirecek şekilde aşağıda güncelle.": "Update the main idea of this guide below in a way that makes you feel the pattern.",
    "Bugünkü fikir veya gözlem": "Today's idea or observation",
    "Devam Et": "Continue",
    "24 Saat Testi": "24 Hour Test",
    "Bu fikri 24 saatten uzun süredir düşünüyor musun?": "Have you been thinking about this idea for more than 24 hours?",
    "Evet, işleme al": "Yes, process it",
    "Hayır, müzeye kaldır": "No, send it to the museum",
    "Döküman & Artıklar": "Document & Leftovers",
    "GÖRSEL": "VISUAL",
    "SES": "AUDIO",
    "YAZI": "TEXT",
    "Ham malzeme": "Raw material",
    "Amatör Modu": "Amateur Mode",
    "Hata yapmaktan korkma. En ham halini paylaş.": "Don't be afraid to make mistakes. Share the rawest version.",
    "Paylaşacağım →": "I will share →",
    "Müzeye al": "Send to museum",
    "So What? Testi": "So What? Test",
    "Sturgeon Yasası:": "Sturgeon's Law:",
    "Her şeyin %90'ı çöptür. Neyin iyi neyin kötü olduğunu hemen bilemeyebilirsin.": "90% of everything is crap. You may not immediately know what is good and what is bad.",
    "Bir kıvılcım — devam": "A spark — continue",
    "Emin değilim": "I'm not sure",
    "Sadece gürültü — sil": "Just noise — delete",
    "← İptal": "← Cancel",
    "Rehber Bağlamı": "Guide Context",
    "DVD Ekstrası gibi düşün:": "Think like a DVD Extra:",
    "Bunlar sınav soruları değil. İki cümle yeter — Kleon der ki \"dünyanın senden istediği şey sadece kısa bir açıklamadır.\"": "These are not exam questions. Two sentences are enough — Kleon says \"what the world wants from you is just a brief explanation.\"",
    "Hikaye": "Story",
    "— geçmiş · şimdi · gelecek": "— past · present · future",
    "Özetleniyor...": "Summarizing...",
    "Kaydı Bitir": "End Recording",
    "Sesli Anlat (AI Özetlesin)": "Tell with voice (Let AI summarize)",
    "Müze Etiketi": "Museum Tag",
    "(isteğe bağlı)": "(optional)",
    "✓ link var": "✓ has link",
    "İsim verdin ama link yok — Kleon'a göre linksiz atıf internette neredeyse görünmez.": "You gave a name but no link — according to Kleon, attribution without a link is almost invisible on the internet.",
    "Henüz uzman değilim, deneme yanılma yapıyorum": "I'm not an expert yet, I'm doing trial and error",
    "Harmanla →": "Blend →",
    "Önizleme →": "Preview →",
    "DÜZENLENEBİLİR": "EDITABLE",
    "SÜSLE": "DECORATE",
    "Kleon der ki:": "Kleon says:",
    "\"İyi bir fikir asla tam bitmez, sadece yayınlanır.\" Hatalarıyla kucakla. Bu senin": "\"A good idea is never completely finished, it just gets published.\" Embrace it with its flaws. This is your",
    "stoğun": "stock",
    "Yayın Platformu": "Publishing Platform",
    "Kendi Web Sitem — Karargah": "My Website — HQ",
    "X (Twitter) — Uydu": "X (Twitter) — Satellite",
    "LinkedIn — Profesyonel Uydu": "LinkedIn — Professional Satellite",
    "Substack — Bülten Köşesi": "Substack — Newsletter Corner",
    "Vampir Testi": "Vampire Test",
    "Veri toplanıyor...": "Collecting data...",
    "VAMPİR UYARISI": "VAMPIRE WARNING",
    "Metriklerin kölesi olduklarında yaratıcılıkları öldü.": "Their creativity died when they became slaves to metrics.",
    "Mükemmeliyetçilik Bir Hapishanedir:": "Perfectionism is a Prison:",
    "Öleceksin. Bu yüzden bu kusurlu haliyle yayınla. Gerçek başarı sürekliliktedir.": "You will die. So publish it in its flawed state. True success is in continuity.",
    "Gözünü kapat ve yayınla": "Close your eyes and publish",
    "Kalıcı Bir Değer Yarattın": "You Created a Permanent Value",
    "\"Fikirlerinizi stoklayın. Onları biriktirin, düzenleyin ve başkalarına fayda sağlayacak bir bütüne dönüştürün.\"": "\"Stock your ideas. Collect them, organize them, and turn them into a whole that will benefit others.\"",
    "— Austin Kleon, Show Your Work": "— Austin Kleon, Show Your Work",
    "Bugün bir iz bıraktın.": "You left a mark today.",
    "Austin Kleon: \"Başkalarının işlerini çalın, kendi stilinizi harmanlayın.\"": "Austin Kleon: \"Steal other people's work, blend your own style.\"",
    "Sabbatical Başladı:": "Sabbatical Started:",
    "Cihazları kapat. Bir ağaca bak. Köpeğini gezdir.": "Turn off the devices. Look at a tree. Walk your dog.",
    "Hemingway Taktiği — yarın kaldığın yerden devam et:": "Hemingway Tactic — continue where you left off tomorrow:",
    "Kaydet & Sabbatical'a çık": "Save & Go on Sabbatical",
    "Geri Dön": "Go Back"
};

const fs = require('fs');
let context = fs.readFileSync('src/contexts/LanguageContext.tsx', 'utf8');

// Insert the translations into the english dictionary at the end of the `en:` object
let replacement = '';
for (const [tr, en] of Object.entries(obj)) {
    replacement += `    '${tr.replace(/'/g, "\\'")}': '${en.replace(/'/g, "\\'")}',\n`;
}

// Find `// App & Global` in `en: {` and push it there
context = context.replace(/('move\.new_ph': 'e\.g: inspiration-board',)/, `$1\n    // Auto-extracted components\n${replacement}`);

fs.writeFileSync('src/contexts/LanguageContext.tsx', context);
