import React, { createContext, useContext, useState, useEffect } from 'react';

type Language = 'tr' | 'en';

interface LanguageContextType {
  lang: Language;
  setLang: (lang: Language) => void;
  t: (key: string, args?: Record<string, string | number>) => string;
}

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

const translations: Record<Language, Record<string, string>> = {
  tr: {
    // Navigation
    'nav.flow': 'Akış',
    'nav.cabinet': 'Merak Kabinesi',
    'nav.hub': 'Dünya Karargahı',
    'nav.profile': 'Profil',
    'nav.title': 'Amateur Scenius',
    'nav.subtitle': 'Müze Rehberi',
    'nav.login': 'Giriş Yap',
    'nav.music_play': '🎵 Lo-Fi Oyna',
    'nav.music_stop': '🎵 Lo-Fi Kapat',
    'nav.credits': 'Mühendisin Kitaplığı tarafından yapıldı',
    // Profile
    'profile.title': 'Sana Ait Alan',
    'profile.subtitle': 'Menzili uzun yolculuklarda, en güçlü karargah kişinin kendi kimliğidir.',
    'profile.age': 'Yaş: 24',
    'profile.sync_active': 'Senkronizasyon Aktif',
    'profile.sync_desc': 'Tüm notların ve fikirlerin Firebase bulutunda güvenle saklanıyor. İstediğin cihazdan erişebilirsin.',
    'profile.logout': 'Karargahtan Çıkış Yap',
    'profile.guest_mode': 'Misafir Modundasın',
    'profile.guest_desc': 'Şu anki fikirlerin sadece bu tarayıcıda geçici olarak saklanıyor. Kalıcı olarak depolamak ve senkronize etmek için giriş yapmalısın.',
    'profile.login_btn': 'Google ile Giriş Yap',
    'profile.credits': 'Mühendisin Kitaplığı tarafından geliştirilmiştir.',

    // Hub
    'hub.title': 'Dünya Karargahı',
    'hub.subtitle': 'Sosyal ağlar gelip geçicidir. Asıl mülkiyet senin alan adında. Diğerleri sadece birer uydu.',
    'hub.domain': 'SENİN\nALAN ADIN',
    'hub.content_flow': '↕ İÇERİK AKIŞI',
    'hub.p1_name': 'Kendi Web Sitem',
    'hub.p1_desc': 'sağlıklı karargah',
    'hub.p2_name': 'X (Twitter) — Uydu',
    'hub.p2_desc': 'sağlıklı uydu',
    'hub.p3_name': 'LinkedIn — Uydu',
    'hub.p3_desc': 'sağlıklı uydu',
    'hub.p4_name': 'Instagram',
    'hub.p4_desc': 'vampir uyarısı',
    'hub.published': 'YAYINLANMIŞ ESERLER',
    'hub.empty': 'Henüz dünyaya açılan bir eserin yok. Hemen bir tane harmanla.',
    'hub.blended': '📝 HARMANLANMIŞ HİKAYE',
    'hub.hq': 'Karargah',
    'hub.note_title': 'Dünya Karargahı Notu:',
    'hub.note_body': ' İstatistikler enerjini nasıl yönettiğine dair bir aynadır. Sosyal ağlar seni değil, sen onları kullanmalısın.',

    // Auth
    'auth.err_email': 'Geçersiz e-posta adresi.',
    'auth.err_cred': 'E-posta veya şifre hatalı.',
    'auth.err_in_use': 'Bu e-posta kullanımda.',
    'auth.err_weak': 'Şifre en az 6 karakter olmalıdır.',
    'auth.err_disabled': 'E-posta ile giriş kapalı! Lütfen Firebase Konsolundan açın.',
    'auth.reset_sent': 'Şifre sıfırlama e-postası gönderildi. Spam kutusunu kontrol etmeyi unutmayın!',
    'auth.subtitle': 'süreci düşün, ürünü değil',
    'auth.welcome': 'Tekrar Hoş Geldin!',
    'auth.signup': 'Kayıt Ol',
    'auth.forgot': 'Şifremi Unuttum',
    'auth.desc_sign_in': 'Seni özlemiştik, devam edelim',
    'auth.desc_sign_up': 'Notlarını kalıcı olarak saklamak için hesap oluştur',
    'auth.desc_forgot': 'E-posta adresini gir, sıfırlama linki gönderelim',
    'auth.email': 'E-posta Adresi',
    'auth.password': 'Şifre',
    'auth.forgot_q': 'Şifremi Unuttum?',
    'auth.send_link': 'Bağlantı Gönder',
    'auth.or': 'veya şununla devam et',
    'auth.back': 'Geri Dön',
    'auth.no_account': 'Hesabın yok mu?',
    'auth.has_account': 'Zaten hesabın var mı?',
    'auth.guest': 'Misafir olarak devam et →',

    // App & Global
    'app.confirm_publish': 'Bu eseri yayınlamak istediğinize emin misiniz?',
    'app.confirm_delete_all': 'Tüm veriler silinecek. Emin misin?',
    'app.confirm_delete_tag': '"{tag}" etiketine ait tüm eserler silinecek. Emin misin?',
    'dialog.cancel': 'Vazgeç',
    'dialog.delete': 'Sil',
    'dialog.move': 'Taşı',
    'move.title': 'Kategoriyi Değiştir',
    'move.desc': 'Bu fikri hangi etikete taşımak istiyorsunuz?',
    'move.existing': 'Var Olanlar',
    'move.new': 'Yeni Oluştur',
    'move.no_tags': 'Taşınabilecek başka var olan etiket bulunamadı.',
    'move.new_label': 'YENİ ETİKET ADI',
    'move.new_ph': 'örn: ilham-panosu',
    'common.understood': 'Anladım, Teşekkürler',
    'common.back': 'Geri Dön',
    'common.cancel': 'Vazgeç',
    'common.delete': 'Sil',
    'common.save': 'Kaydet',
    'common.continue': 'Devam Et',
    'common.publish': 'Yayınla',
    'common.loading': 'Yükleniyor...',

    // Cabinet
    'cabinet.all_ideas': 'Tümü',
    'cabinet.starred': 'Yıldızlılar',
    'cabinet.drafts': 'Taslaklar',
    'cabinet.published_tab': 'Yayınlananlar',
    'cabinet.stock_piled': 'Stok Birikti — {tag}',
    'cabinet.stock_alert_title': '📦 Stok Birikti!',
    'cabinet.items_count': 'Eser',
    'cabinet.ideas_selected': '{count} eser seçildi',
    'stock.step_0_title': 'ADIM 0 — Zaman Çizgisi + Seçim',
    'stock.step_0_desc': 'Birleştirmek istediğin fikirleri seç. Kleon felsefesi: "Noktaları birleştir, bütünü gör."',
    'stock.select_at_least_2': 'En az 2 fikir seç',
    'stock.merge_ideas': 'Fikri Birleştir →',
    'stock.step_1_title': 'ADIM 1 — ÖRÜNTÜ BULUNDU',
    'stock.common_points': 'Seçtiğin {count} fikir arasındaki ortak noktalar:',
    'stock.step_1_desc': 'Aşağıdaki kelimeler seçtiğin fikirlerde en çok geçen örüntülerdir. Rehberinde vurgulamak istediklerini onayla.',
    'stock.system_suggestion': 'SİSTEM ÖNERİSİ',
    'stock.system_suggestion_desc': 'Bu fikirler ve onayladığın kelimeler en çok şu şablona uyuyor:',
    'stock.kleon_quote_structure': 'Kleon der ki: "Rehberin yapısı içindeki örüntüye göre şekillenir."',
    'stock.continue_with_approved': 'Onayladıklarımla Devam Et →',
    'stock.step_2_title': 'ADIM 2 — Şablonu Kesinleştir',
    'stock.step_2_desc': 'Önerilen şablon en uygunu gibi görünüyor, ancak istersen başka bir tane seçebilirsin.',
    'stock.suggested_badge': 'ÖNERİLEN',
    'stock.start_writing': 'Seçili Şablonla Yazmaya Başla →',
    'stock.step_3_title': 'ADIM 3 — Rehberi Oluştur',
    'stock.how_to_answer': 'NASIL CEVAPLAMALIYIM?',
    'stock.how_to_answer_desc': 'Aşağıdaki her bir soru, seçtiğin notları harmanlaman için bir rehberdir. Notlarına tıklayarak metinleri kutuya ekleyebilir, sonra kendi cümlelerinle onları birleştirip akıcı bir hikaye oluşturabilirsin.',
    'stock.textarea_placeholder': 'Notlarından ilham alarak burayı doldur...',
    'stock.reference_notes': 'Referans Alınacak Notların (Tıkla ve Ekle):',
    'stock.preview_and_publish': 'Önizleme ve Yayınla →',
    'stock.step_4_title': 'ADIM 4 — SON DOKUNUŞLAR',
    'stock.completed_guide': 'Tamamlanmış Rehberin',
    'stock.success_title': 'Muazzam Stok Eritme!',
    'stock.success_desc_start': 'Seçtiğin fikirleri birleştirerek',
    'stock.success_desc_end': 'üzerine harika bir rehber oluşturdun. Austin Kleon gurur duyardı!',
    'stock.return_to_cabinet': 'Kabineye Dön',
    'cabinet.delete_selected': 'Seçiliyi Sil ({count})',
    'cabinet.delete_all_tag': 'Kategorideki Tümünü Sil',
    'cabinet.no_ideas': 'Burada hiç fikir yok.',
    'cabinet.empty_category': 'Bu kategoride henüz bir müze objesi yok.',
    'cabinet.searching_lost_works': 'Kayıp eserler aranıyor...',
    'cabinet.items_count': '{count} eser',
    'cabinet.close': 'KAPAT',
    'cabinet.museum_tag': 'MÜZE ETİKETİ',
    'cabinet.published': 'yayınlandı',
    'cabinet.draft': 'taslak',
    'cabinet.hemingway_tactic': 'Hemingway Taktiği',
    'cabinet.draft_incomplete': 'Bu taslak yarım kalmış. Kaldığın yerden devam etmek için aşağıdaki butona bas — fikir Akış\'a yüklenecek.',
    'cabinet.continue_today': 'Bugün Devam Et',
    'cabinet.museum_artifacts': 'MÜZE ESERLERİ',
    'cabinet.view': 'Görüntüle',
    'cabinet.attribution_source': 'ATIF — İLHAM KAYNAĞI',
    'cabinet.revisit_note': 'Yeniden Ziyaret Notu',
    'cabinet.revisit_placeholder': 'Bu fikir bugün ne anlam taşıyor?',
    'cabinet.starred': 'Yıldızlı',
    'cabinet.star': 'Yıldızla',
    'cabinet.change_category': 'Kategoriyi Değiştir',
    'cabinet.delete_artifact': 'Eseri Sil',
    'cabinet.template_modal_artifact': 'ESER',
    'cabinet.start_answer': 'Başla — Soruları Cevapla',
    'cabinet.cancel': 'Vazgeç',
    'cabinet.honest_answer': 'Her soruyu dürüstçe cevapla. Mükemmel olmasına gerek yok.',
    'cabinet.finish_and_save': 'Bitir ve Kabineye Sakla',
    'common.back': '← Geri Dön',
    'common.edit': '← Düzenle',
    'common.publish_check': 'Yayınla ✓',
    'cabinet.start_wizard': 'Start Wizard',
    'wizard.idea_notebook_title': 'Fikir Defteri',
    'wizard.playbook_btn': '✦ Kleon Playbook',
    'wizard.pattern_finding': 'Örüntü (Pattern) Bulma',
    'wizard.kleon_pattern_wizard': 'Kleon der ki: "Bu içeriklere yukarıdan bak. Ortak nokta ne? Aynı dili mi kullanıyorlar, aynı hatayı mı çözüyorlar?"',
    'wizard.task_label': 'Görev:',
    'wizard.task_desc': 'Bu rehberin ana fikrini, örüntüyü hissettirecek şekilde aşağıda güncelle.',
    'wizard.idea_label': 'Bugünkü fikir veya gözlem',
    'wizard.idea_placeholder': 'Bugün aklıma şu geldi...',
    'wizard.idea_placeholder_tag': '{tag} üzerine çalışmaya devam et...',
    'wizard.tags_label': 'Etiketler',
    'wizard.test_24h_title': '24 Saat Testi',
    'wizard.test_24h_desc': 'Bu fikri 24 saatten uzun süredir düşünüyor musun?',
    'wizard.test_24h_yes': 'Evet, işleme al',
    'wizard.test_24h_no': 'Hayır, müzeye kaldır',
    'wizard.doc_title': 'Döküman & Artıklar',
    'wizard.media_image': 'GÖRSEL',
    'wizard.media_audio': 'SES',
    'wizard.media_text': 'YAZI',
    'wizard.raw_material_label': 'Ham malzeme',
    'wizard.raw_material_ph': 'Kod, not, karalama...',
    'wizard.amateur_mode_label': 'Amatör Modu',
    'wizard.amateur_mode_desc': 'Hata yapmaktan korkma. En ham halini paylaş.',
    'wizard.share_btn': 'Paylaşacağım →',
    'wizard.museum_btn': 'Müzeye al',
    'wizard.so_what_title': 'So What? Testi',
    'wizard.sturgeon_law': 'Sturgeon Yasası:',
    'wizard.sturgeon_desc': "Her şeyin %90'ı çöptür. Neyin iyi neyin kötü olduğunu hemen bilemeyebilirsin.",
    'wizard.spark_continue': 'Bir kıvılcım — devam',
    'wizard.not_sure_btn': 'Emin değilim',
    'wizard.noise_delete': 'Sadece gürültü — sil',
    'wizard.draft_saved': '24 saat geçmedi — taslak saklandı.',
    'wizard.gathering_data_auth': 'GÜVENİLİR BİLGİ',
    'wizard.draft_stored': 'Taslak saklandı.',
    'wizard.delete_confirm': 'Emin misiniz?',
    'wizard.deleted_msg': 'Silindi.',

    // Wizard & Info Modals
    'wizard.info_title': 'Fikir Defteri',
    'wizard.info_stolen': 'Yaratıcı Hırsızlık',
    'wizard.info_stolen_quote': '"İyi bir sanatçı kopyalamaz, çalar." — Austin Kleon',
    'wizard.info_desc1': 'Burası senin fikirlerinin tohumlandığı yer. Aklına gelen her şeyi not al, etiketle ve sakla.',
    'wizard.info_desc2': 'Fikirlerini daha sonra Merak Kabinesi\'nde harmanlayabilir, buradaki Kleon Playbook ile yaratıcılığını artıracak taktikler öğrenebilirsin.',
    'wizard.playbook': '✦ Kleon Playbook',
    'wizard.suggest_ai': 'AI Öner',
    'wizard.summarize_ai': 'Fikri Özetle',
    'wizard.note_name': 'NOT ADI',
    'wizard.note_placeholder': 'Notlarını buraya yaz...',
    'wizard.no_empty': 'Boş fikir kaydedilemez.',
    'wizard.save_failed': 'Taslak saklandı.',
    'wizard.save_success': '24 saat geçmedi — taslak saklandı.',
    'wizard.bilgi': 'Bilgi',
    'wizard.mikrofon_hata': 'Mikrofona erişilemedi.',
    'wizard.step_title_0': 'Fikir',
    'wizard.step_title_1': '24h',
    'wizard.step_title_2': 'Döküm',
    'wizard.step_title_3': 'S.W?',
    'wizard.step_title_4': 'Form',
    'wizard.step_title_5': 'Önizleme',
    'wizard.step_title_6': 'Kontrol',
    'wizard.step_title_7': 'End',
    
    // Hub Info
    'hub.info_title': 'Domain Sahibi Ol',
    'hub.info_quote': '"Sosyal ağlar birer uydudur. Karargahın ise senin kontrolünde olmalıdır." — Austin Kleon',
    'hub.info_desc1': 'Burası senin klanını topladığın yer. Tüm yayınlarını buradan yönet. Social Graph (Sosyal Grafiğini) burada kendin kontrol edersin.',
    'hub.info_desc2': 'Paylaşımlarının ne kadar enerji tükettiğini (Vampir Testi) ve hangi platformlarda ne kadar etki yarattığını buradan takip edebilirsin.',

    // Cabinet Info
    'cabinet.info_title': 'Wunderkammern',
    'cabinet.info_quote': '"Zevklerin seni sen yapan şeydir. Toplamak yaratmayı besler." — Austin Kleon',
    'cabinet.info_desc1': 'Burası senin müzen. Tüm fikirlerin burada gruplanmış halde durur. Austin Kleon\'un merak kabinesi felsefesini burada uygula.',
    'cabinet.info_desc2': 'Fikirlerini etiketlerine göre filtreleyebilir, belli bir kavrama yönelik yazdığın tüm notları tek seferde görebilirsin. Eğer bir etikette 3 veya 10 nota ulaşırsan, biriken notları tek tıklamayla harmanlayıp rehberlere (taslaklara) dönüştürebilirsin!',

    // Templates
    'template.technical.label': 'Adım Adım Teknik Rehber',
    'template.technical.headline': 'Aaron Franklin Stili — Mutfağını Paylaş',
    'template.technical.body': 'Aaron Franklin her yıl barbekü tekniklerini anlatan saatler uzunluğunda videolar yayınlar. Sadece sonucu değil, fire build\'i, et seçimini, sıcaklık kontrolünü — her aşamayı. Okuyucu seni "izleyerek" aynı sonuca ulaşabilmeli.',
    'template.technical.quote': '"İnsanlara nasıl yapıldığını göstermek, onları hem aydınlatır hem de sana bağlar." — Austin Kleon',
    'template.technical.when': 'Bu 6 içerik birbirini takip eden adımlarsa kullan.',

    'template.documentary.label': '"Nasıl Yaptım?" Belgeseli',
    'template.documentary.headline': 'Sucuğun Nasıl Yapıldığını Göster',
    'template.documentary.body': 'İnsanlar "sucuğun nasıl yapıldığını" görmek ister. Sadece sonucu değil, mutfağı paylaş. Karşılaştığın duvarları, çıkmaz sokakları, "ikinci perde" zorluklarını — Kleon\'un dediği "throwing rocks" anlarını — açık yüreklilikle yaz. Bu seni güvenilir kılar.',
    'template.documentary.quote': '"Başarı hikayeleri ilham verir, ama hata hikayeleri öğretir." — Austin Kleon',
    'template.documentary.when': 'Bu içerikler bir projenin farklı aşamalarındaki hataları ve başarıları temsil ediyorsa kullan.',

    'template.readingList.label': 'İlham ve Atıf Kitapçığı',
    'template.readingList.headline': 'Açık Düğüm (Open Node) Ol',
    'template.readingList.body': 'Kleon, kaynaklarını paylaşmanın seni "açık bir düğüm" yaptığını söyler — topluluğun içinde bir kavşak noktasısın. Seni besleyen kitapları, videoları, kişileri paylaştığında, başkalarına kendi öğrenme yolculuklarında harita veriyorsun.',
    'template.readingList.quote': '"Başkalarına yol göster, onlar da seni takip eder." — Austin Kleon, Show Your Work',
    'template.readingList.when': 'Bu içerikler öğrendiğin kaynaklar, okuduğun dokümanlar veya başkalarından kaptığın fikirlerden oluşuyorsa kullan.',

    'template.oldVsNew.label': '"Eski vs. Yeni" Gelişim Şablonu',
    'template.oldVsNew.headline': 'Amatörlükten Ustalığa Yolculuk',
    'template.oldVsNew.body': '"Bu işe başladığımda ne bilmiyordum, şu an neyi farklı yapıyorum?" kıyaslaması, okuyucuya hem mütevazılık hem de ilham verir. Yanlış inançlarını, yanılgılarını, köşe dönümlerini paylaş. Amatörlük bir başlangıç noktasıdır, utanılacak bir şey değil.',
    'template.oldVsNew.quote': '"Amatör olmak bir ayrıcalıktır — henüz merakı öldürülmemiş birisin." — Austin Kleon',
    'template.oldVsNew.when': 'Bu içerikler zaman içindeki değişimini gösteriyorsa — erken dönem vs. şimdiki hali — kullan.',

    // Guide Fields
    'guide.technical.tools.label': 'Araçlar, Kütüphaneler & Materyaller',
    'guide.technical.tools.hint': 'Aaron Franklin\'in barbekü videolarında her aleti tek tek gösterdiği gibi — okuyucu bu listeyle hazırlığını yapabilmeli.',
    'guide.technical.tools.ph': 'Örn: VS Code, Node.js v20, Tailwind CSS, Railway.app — her aracın adını ve neden tercih ettiğini yaz.',
    
    'guide.technical.s1.label': 'Aşama 1 — Hazırlık & Kurulum (Fire Build)',
    'guide.technical.s1.hint': 'Franklin önce ateşi nasıl yakacağını anlatır. Sen de sıfırdan nasıl başladığını göster. Ne kuruldu, ne yapılandırıldı?',
    'guide.technical.s1.ph': 'Sıfırdan başlamak için ilk adım neydi? Kurulum, yapılandırma, proje iskeletini oluşturma...',
    
    'guide.technical.s2.label': 'Aşama 2 — Asıl İş & Ticari Sırlar',
    'guide.technical.s2.hint': '"Normalde kimse şunu söylemez ama..." ile başla. Franklin bu kısımda hiçbir tarif kitabında olmayan sıcaklık kontrolü tüyolarını paylaşır.',
    'guide.technical.s2.ph': 'Asıl iş nasıl ilerledi? Hangi ipuçları fark yarattı? Başkalarının söylemediği ne var?',
    
    'guide.technical.s3.label': 'Aşama 3 — Sonuç, Hatalar & Bir Dahaki Sefere',
    'guide.technical.s3.hint': 'Sadece "çalıştı" deme. Neyin beklenmedik şekilde işe yaramadığını, ne düzelttiklerini de yaz. Bu dürüstlük güven inşa eder.',
    'guide.technical.s3.ph': 'Sonuç nasıl çıktı? Hangi hatalar yapıldı? Aynı işi tekrar yapsan ne değiştirirdin?',
    
    'guide.documentary.target.label': 'Başlangıç Hedefi & Niyet',
    'guide.documentary.target.hint': 'Kleon der ki: "Başladığın yer ile bitirdiğin yerin farklı olması, senin dürüstlüğünü gösterir." Ne yapmak istiyordun?',
    'guide.documentary.target.ph': 'Bu projeye / fikre başlarken ne hayal ediyordun? Hangi sorunu çözmek istiyordun?',
    
    'guide.documentary.difficulties.label': 'Throwing Rocks — İkinci Perde Zorlukları',
    'guide.documentary.difficulties.hint': '"Throwing rocks" = hikayenin ortasındaki engeller. Protagonist (sen) bunları aşmak zorunda. Hataları, çıkmaz sokakları, "hiç çalışmadı" anlarını utanmadan yaz.',
    'guide.documentary.difficulties.ph': 'Nerede tökezledin? Hangi varsayımların yanlış çıktı? Neler planlandığı gibi gitmedi? Ne kadar zaman kaybettin?',
    
    'guide.documentary.lessons.label': 'Sürecin Öğrettikleri & Çözüm',
    'guide.documentary.lessons.hint': 'İyi bir belgesel kahramanın dönüşümünü gösterir. "Bunu yaşayarak öğrendim ki..." ile başla.',
    'guide.documentary.lessons.ph': 'Sonunda ne elde ettin? Bu deneyim seni nasıl değiştirdi? Bir dahaki sefere ne yapardın?',
    
    'guide.readingList.sources.label': 'Kitaplar & Makaleler',
    'guide.readingList.sources.hint': '"Açık düğüm olmak" = başkalarına yol göstermek. Her kaynağın neden önemli olduğunu bir cümleyle açıkla. Sadece liste yapma.',
    'guide.readingList.sources.ph': 'Örn:\n- "Show Your Work" — Kleon (paylaşım korkusunu kırdı)\n- stripe.com/docs (en iyi API dökümantasyonu)\nLink ver, neden önerdiğini yaz.',
    
    'guide.readingList.multimedia.label': 'Videolar, Podcastler & Kurslar',
    'guide.readingList.multimedia.hint': 'Birisi 30 dakika harcayacaksa, neden bu içeriği seçmeli? Kendine sor: "Bu benim için ne değiştirdi?"',
    'guide.readingList.multimedia.ph': 'Örn:\n- Fireship YouTube (10 dakikada kavramı öğretti)\n- Syntax.fm Podcast — Ep.123 (deployment sorunuma çözüm buldu)',
    
    'guide.readingList.follows.label': 'Açık Düğümler — Kimler Takip Edilmeli?',
    'guide.readingList.follows.hint': 'Kleon der ki: "Seni besleyen insanlara işaret et. Bu seni küçültmez, tam tersine ağına katar." Her isim için "çünkü" diye açıkla.',
    'guide.readingList.follows.ph': 'Örn:\n- @kentcdodds — çünkü test yazımını demokratikleştirdi\n- Cassidy Williams — çünkü "amatörce" paylaşımın gücünü gösteriyor',
    
    'guide.oldVsNew.oldWay.label': 'Eskiden Ne Biliyordum? Hangi Yanlış İnançlarım Vardı?',
    'guide.oldVsNew.oldWay.hint': 'Kleon der ki: "Amatörlük bir başlangıç noktasıdır, utanılacak bir şey değil." Eski yanlışlarını paylaşmak okuyucuya "ben de yapabilirim" dedirtir.',
    'guide.oldVsNew.oldWay.ph': 'Bu işe başladığımda şunlara inanıyordum:\n- Her şeyi anlamadan başlayamazdım (yanlış)\n- Kod "mükemmel" olmalıydı (yanlış)\n- Paylaşmak için "hazır" olmam gerekiyordu (yanlış)',
    
    'guide.oldVsNew.newWay.label': 'Şu An Neyi Farklı Yapıyorum? Kırılma Anım Ne Oldu?',
    'guide.oldVsNew.newWay.hint': 'Sadece "şimdi daha iyiyim" deme. Tam olarak ne değişti, ne zaman döndü? Somut bir "eureka" anı varsa onu anlat.',
    'guide.oldVsNew.newWay.ph': 'Kırılma noktam şuydu:\n- Bir hata mesajını 3 saat uğraştıktan sonra çözdüğümde...\nŞimdi farklı yaptığım şeyler:\n- Hataları "öğretmen" olarak görüyorum\n- Ham halleriyle paylaşıyorum',

    'Anladım, Teşekkürler': 'Anladım, Teşekkürler',
    'cabinet.delete_confirm': '{label} silmek istediğinize emin misiniz?',
    'Emin misiniz?': 'Emin misiniz?',
    'En az 2 fikir seç': 'En az 2 fikir seç',
    'Fikri Birleştir →': 'Fikri Birleştir →',
    'Seçtiğin {count} fikir arasındaki ortak noktalar:': 'Seçtiğin {count} fikir arasındaki ortak noktalar:',
    'tour.skip': 'Geç',
    'tour.prev': 'Geri',
    'tour.next': 'Devam Et',
    'tour.finish': 'Başla ✦',
    'tour.step1.title': '1. Giriş: Fikir Defteri',
    'tour.step1.phil': 'Felsefe',
    'tour.step1.quote': '"Austin Kleon der ki: Deha olmanıza gerek yok. Yaratıcılık, kendinizi bir \'scenius\' içinde konumlandırmaktır."',
    'tour.step1.desc': 'Buraya en küçük gözlemini bile yaz. Amatörler, kaybedecek bir şeyi olmadığı için denemekten çekinmezler.',
    'tour.step2.title': '2. Etiketler: Gruplandır',
    'tour.step2.desc': 'Aynı etiketteki fikirler zamanla birikerek bir <strong>Stok (Stock)</strong> oluşturur. Austin Kleon\'un tavsiyesi: Ortak noktaları bul ve onları birleştir.',
    'tour.step2.hint': 'Devam Et butonuna basarak ilerleyebilirsin.',
    'tour.step3.title': '3. 24 Saat Testi',
    'tour.step3.phil': 'Austin Kleon',
    'tour.step3.quote': '"Her şeyi anında paylaşmak insan spam\'ine yol açabilir."',
    'tour.step3.desc': 'Fikri 24 saat beklet. Hâlâ heyecan veriyorsa işleme al, yoksa <strong>Müzeye Kaldır</strong>.',
    'tour.step3.ways': 'İki yol var:',
    'tour.step3.way1': '✅ <strong>Evet, işleme al</strong> → Döküman adımına geçer',
    'tour.step3.way2': '🏛️ <strong>Müzeye Kaldır</strong> → Taslak saklanır, tur biter',
    'tour.step4.title': '4. Döküman & Artıklar',
    'tour.step4.phil': 'Süreci Paylaş',
    'tour.step4.quote': '"Sucuğun nasıl yapıldığını göster. Artıklar (residue), ürünün kendisi kadar değerlidir."',
    'tour.step4.desc': 'Görsel ekle, ses kaydı al veya yazı notları tut.',
    'tour.step4.way1': '📤 <strong>Paylaşacağım →</strong> So What? testine geçer',
    'tour.step4.way2': '🏛️ <strong>Müzeye Al</strong> → Taslak saklanır, tur biter',
    'tour.step5.title': '5. Ham Madde',
    'tour.step5.desc': 'Kod parçaları, karalamalar veya ham notlarını buraya dök. Austin Kleon\'a göre <em>"Ham halini paylaşmak dürüstlüktür."</em>',
    'tour.step6.title': '6. So What? Testi',
    'tour.step6.phil': 'Cömertlik',
    'tour.step6.quote': '"Paylaşım bir cömertlik eylemidir, ego tatmini değil."',
    'tour.step6.desc': 'Kendine sor: Bu başkası için yararlı mı?',
    'tour.step6.ways': 'Üç yol var:',
    'tour.step6.way1': '✨ <strong>Bir kıvılcım — devam</strong> → Hikaye adımına geçer',
    'tour.step6.way2': '🏛️ <strong>Emin değilim</strong> → Taslak saklanır',
    'tour.step6.way3': '🗑️ <strong>Sadece gürültü — sil</strong> → Fikir silinir',
    'tour.step7.title': '7. Hikaye & Bağlam',
    'tour.step7.phil': 'Austin Kleon',
    'tour.step7.quote': '"İş kendi başına konuşmaz. İnsanlar hikayeyi bilmek isterler."',
    'tour.step7.desc': 'Geçmişte ne hedefledin, şimdi neredesin? İki cümle yeter — hikayeni buraya yaz.',
    'tour.step8.title': '8. Atıf Adabı',
    'tour.step8.phil': 'Dürüstlük',
    'tour.step8.quote': '"Atıf İnternet\'in ana para birimidir. Linksiz atıf neredeyse görünmezdir."',
    'tour.step8.desc': 'İlham aldığın kişiyi ve kaynağı belirt. Sonra <strong>Harmanla →</strong> butonuna bas.',
    'tour.step9.title': '9. Harmanlanan Hikaye',
    'tour.step9.phil': 'Son Rötuş',
    'tour.step9.quote': '"İyi bir fikir asla tam bitmez, sadece yayınlanır." — Kleon',
    'tour.step9.desc': 'Aşağıdaki alandan metni düzenleyebilir veya ✨ <strong>AI Süsle</strong> butonuyla zenginleştirebilirsin. Sonra <strong>Devam →</strong> butonuna bas.',
    'tour.step10.title': '10. Vampir Testi',
    'tour.step10.phil': 'Enerji Kontrolü — Austin Kleon',
    'tour.step10.quote': '"Vampir testi basittir: Bir şey seni enerjik hissettiriyorsa, devam et. Seni tüketiyorsa, bırak."',
    'tour.step10.desc1': 'Kleon\'a göre mükemmeliyetçilik en büyük vampirdir. Beğeni sayısı, retweet beklentisi — bunlar yaratıcılığını öldürür.',
    'tour.step10.desc2': 'Fikrinin seni besleyip beslemediğini kontrol et. Hazırsan <strong>"Gözünü kapat ve yayınla"</strong> butonuna bas!',
    'tour.step11.title': '11. Yayınla',
    'tour.step11.desc': 'Gözünü kapat ve yayınla. Gerçek başarı süreklilikte ve ham haliyle paylaşabilme cesaretindedir.',
    'tour.step11.hint': 'Butona tıkla ve yayınla!',
    'tour.step12.title': '12. Hemingway Tekniği',
    'tour.step12.phil': 'Süreklilik',
    'tour.step12.quote': '"Hemingway, ertesi gün nereye gideceğini bildiğinde yazmayı bırakırdı."',
    'tour.step12.desc': 'Yarın nereden başlayacağını yaz. Bu metot, <em>writer\'s block</em>\'u ortadan kaldırır.',
    'tour.step13.title': '13. Merak Kabinesi',
    'tour.step13.phil': 'Wunderkammern',
    'tour.step13.quote': '"Zevklerin seni sen yapan şeydir. Toplamak yaratmayı besler."',
    'tour.step13.desc': 'Burası senin müzen. Tüm fikirlerin burada gruplanmış halde durur.',
    'tour.step14.title': '14. Etiket Filtreleri',
    'tour.step14.desc': 'Fikirlerini etiketlerine göre filtreleyebilir, belli bir kavrama yönelik yazdığın tüm notları tek seferde görebilirsin.',
    'tour.step15.title': '15. Stok Birikti Uyarıları',
    'tour.step15.desc': 'Eğer bir etikette 3 veya 10 nota ulaşırsan, etiketin üzerinde bir ünlem belirir. Austin Kleon\'un dediği gibi: "Fikirlerini biriktir." Biriken notları tek tıklamayla harmanlayıp rehberlere (taslaklara) dönüştürebilirsin!',
    'tour.step16.title': '16. Seçim',
    'tour.step16.desc': 'Birleştirmek istediğin fikirleri seç. Noktaları birleştirip bütünü görmek ilk adımdır.',
    'tour.step17.title': '17. Örüntü',
    'tour.step17.desc': 'Seçtiğin fikirlerdeki en yaygın kelimeleri incelersin. Rehberinde vurgulamak istediklerini onayla.',
    'tour.step18.title': '18. Şablon Kesinleştirme',
    'tour.step18.desc': 'Bulunan örüntüye en uygun şablonu (Teknik Rehber, Belgesel vs.) sistem otomatik önerir. İstersen değiştirebilirsin.',
    'tour.step19.title': '19. Şablon: Adım Adım Rehber',
    'tour.step19.desc': 'Austin Kleon der ki: "Öğrendiğinde başkalarına da öğret." Bir konuyu nasıl anladığını basit adımlarla kimseye tepeden bakmadan anlatmak için bu kalıbı seç.',
    'tour.step20.title': '20. Şablon: Belgesel',
    'tour.step20.desc': '"Nihai ürünü değil, süreci paylaş." Karşılaştığın zorlukları, kırılma anlarını ve ulaştığın sonuçları hikaye formatında aktarmak için bu şablonu kullan.',
    'tour.step21.title': '21. Şablon: Atıf Kitapçığı',
    'tour.step21.desc': '"Sen, okuduklarının bir karışımısın." Etkilendiğin kaynakları, kimlerden hangi fikirleri çaldığını (alıntıladığını) saygıyla derleyip sunmak içindir.',
    'tour.step22.title': '22. Şablon: Eski vs. Yeni',
    'tour.step22.desc': 'Eski inançlarının nasıl yıkıldığını ve yeni öğrendiklerinle (zıtlıklarla) nasıl yer değiştirdiğini sert geçişlerle göstermek içindir.',
    'tour.step23.title': '23. Rehberi Oluştur',
    'tour.step23.phil': 'Düşünceleri Harmanla',
    'tour.step23.quote': '"Noktaları birleştir, bütünü gör." — Austin Kleon',
    'tour.step23.desc': 'Eski fikirlerini referans alarak yeni ve büyük bir rehber yaz. Aşağıdaki kutularda listelenen ilgili soruları kendi kelimelerinle cevapla.',
    'tour.step23.hint': 'Alt kısımda yer alan <strong>"Seçtiğin fikirlerden"</strong> butonlarına tıklayarak notlarını anında kutuya ekleyebilir, sonra onları kendi cümlelerinle birleştirebilirsin.',
    'tour.step24.title': '24. Son Rötuş ve Yayın',
    'tour.step24.desc': 'Eserini gözden geçir ve istersen Hub\'da yayınla. Austin Kleon\'un tavsiye ettiği gibi stoklarını erittin!',
    'tour.step25.title': '25. Dünya Karargahı',
    'tour.step25.phil': 'Domain Sahibi Ol',
    'tour.step25.quote': '"Sosyal ağlar birer uydudur. Karargahın ise senin kontrolünde olmalıdır."',
    'tour.step25.desc': 'Burası senin klanını topladığın yer. Tüm yayınlarını buradan yönet.',
  },
  en: {
    // Navigation
    'nav.flow': 'Flow',
    'nav.cabinet': 'Cabinet of Curiosities',
    'nav.hub': 'World HQ',
    'nav.profile': 'Profile',
    'nav.title': 'Amateur Scenius',
    'nav.subtitle': 'Museum Guide',
    'nav.login': 'Log In',
    'nav.music_play': '🎵 Play Lo-Fi',
    'nav.music_stop': '🎵 Stop Lo-Fi',
    'nav.credits': 'Made by Mühendisin Kitaplığı',

    // Profile
    'profile.title': 'Your Space',
    'profile.subtitle': 'On long journeys, the strongest headquarters is one\'s own identity.',
    'profile.age': 'Age: 24',
    'profile.sync_active': 'Sync Active',
    'profile.sync_desc': 'All your notes and ideas are securely stored in the Firebase cloud. You can access them from any device.',
    'profile.logout': 'Sign Out from HQ',
    'profile.guest_mode': 'You are in Guest Mode',
    'profile.guest_desc': 'Your current ideas are only temporarily stored in this browser. You must log in to store and sync them permanently.',
    'profile.login_btn': 'Sign In with Google',
    'profile.credits': 'Developed by Mühendisin Kitaplığı',

    // Hub
    'hub.title': 'World HQ',
    'hub.subtitle': 'Social networks come and go. The real ownership is on your domain name. The rest are just satellites.',
    'hub.domain': 'YOUR\nDOMAIN NAME',
    'hub.content_flow': '↕ CONTENT FLOW',
    'hub.p1_name': 'My Website',
    'hub.p1_desc': 'healthy hq',
    'hub.p2_name': 'X (Twitter) — Satellite',
    'hub.p2_desc': 'healthy satellite',
    'hub.p3_name': 'LinkedIn — Satellite',
    'hub.p3_desc': 'healthy satellite',
    'hub.p4_name': 'Instagram',
    'hub.p4_desc': 'vampire alert',
    'hub.published': 'PUBLISHED WORKS',
    'hub.empty': 'You have no works released to the world yet. Blend one right away.',
    'hub.blended': '📝 BLENDED STORY',
    'hub.hq': 'HQ',
    'hub.note_title': 'World HQ Note:',
    'hub.note_body': ' Statistics are a mirror of how you manage your energy. You should use social networks, they shouldn\'t use you.',

    // Auth
    'auth.err_email': 'Invalid email address.',
    'auth.err_cred': 'Invalid email or password.',
    'auth.err_in_use': 'This email is already in use.',
    'auth.err_weak': 'Password must be at least 6 characters.',
    'auth.err_disabled': 'Email login is disabled! Please enable it in Firebase Console.',
    'auth.reset_sent': 'Password reset email sent. Don\'t forget to check your spam folder!',
    'auth.subtitle': 'think process, not product',
    'auth.welcome': 'Welcome Back!',
    'auth.signup': 'Sign Up',
    'auth.forgot': 'Forgot Password',
    'auth.desc_sign_in': 'We missed you, let\'s continue',
    'auth.desc_sign_up': 'Create an account to store your notes permanently',
    'auth.desc_forgot': 'Enter your email, we\'ll send a reset link',
    'auth.email': 'Email Address',
    'auth.password': 'Password',
    'auth.forgot_q': 'Forgot Password?',
    'auth.send_link': 'Send Link',
    'auth.or': 'or continue with',
    'auth.back': 'Go Back',
    'auth.no_account': 'Don\'t have an account?',
    'auth.has_account': 'Already have an account?',
    'auth.guest': 'Continue as Guest →',

    // App & Global
    'app.confirm_publish': 'Are you sure you want to publish this work?',
    'app.confirm_delete_all': 'All data will be deleted. Are you sure?',
    'app.confirm_delete_tag': 'All works belonging to the tag "{tag}" will be deleted. Are you sure?',
    'dialog.cancel': 'Cancel',
    'dialog.delete': 'Delete',
    'dialog.move': 'Move',
    'move.title': 'Change Category',
    'move.desc': 'Which tag do you want to move this idea to?',
    'move.existing': 'Existing',
    'move.new': 'Create New',
    'move.no_tags': 'No other existing tags found to move to.',
    'move.new_label': 'NEW TAG NAME',
    'move.new_ph': 'e.g: inspiration-board',
    'common.understood': 'Understood, Thanks',
    'common.back': 'Back',
    'common.cancel': 'Cancel',
    'common.delete': 'Delete',
    'common.save': 'Save',
    'common.continue': 'Continue',
    'common.publish': 'Publish',
    'common.loading': 'Loading...',

    // Cabinet
    'cabinet.all_ideas': 'All',
    'cabinet.starred': 'Starred',
    'cabinet.drafts': 'Drafts',
    'cabinet.published_tab': 'Published',
    'cabinet.stock_piled': 'Stock Piled — {tag}',
    'cabinet.stock_alert_title': '📦 Stock Piled!',
    'cabinet.items_count': 'Works',
    'cabinet.start_wizard': 'Start Wizard',
    'wizard.idea_notebook_title': 'Idea Notebook',
    'wizard.playbook_btn': '✦ Kleon Playbook',
    'wizard.pattern_finding': 'Pattern Finding',
    'wizard.kleon_pattern_wizard': 'Kleon says: "Look at these contents from above. What is the common thread? Are they using the same language, solving the same mistake?"',
    'wizard.task_label': 'Task:',
    'wizard.task_desc': 'Update the main idea of this guide below to reflect the pattern.',
    'wizard.idea_label': 'Today\'s idea or observation',
    'wizard.idea_placeholder': 'Today I thought this...',
    'wizard.idea_placeholder_tag': 'Continue working on {tag}...',
    'wizard.tags_label': 'Tags',
    'wizard.test_24h_title': '24-Hour Test',
    'wizard.test_24h_desc': 'Have you been thinking about this idea for more than 24 hours?',
    'wizard.test_24h_yes': 'Yes, process it',
    'wizard.test_24h_no': 'No, store in museum',
    'wizard.doc_title': 'Document & Scraps',
    'wizard.media_image': 'IMAGE',
    'wizard.media_audio': 'AUDIO',
    'wizard.media_text': 'TEXT',
    'wizard.raw_material_label': 'Raw material',
    'wizard.raw_material_ph': 'Code, notes, scribbles...',
    'wizard.amateur_mode_label': 'Amateur Mode',
    'wizard.amateur_mode_desc': 'Don\'t be afraid to make mistakes. Share it in its rawest form.',
    'wizard.share_btn': 'I will share →',
    'wizard.museum_btn': 'Store in museum',
    'wizard.so_what_title': 'So What? Test',
    'wizard.sturgeon_law': 'Sturgeon\'s Law:',
    'wizard.sturgeon_desc': "90% of everything is crap. You might not know what's good or bad right away.",
    'wizard.spark_continue': 'A spark — continue',
    'wizard.not_sure_btn': 'I\'m not sure',
    'wizard.noise_delete': 'Just noise — delete',
    'wizard.draft_saved': '24 hours haven\'t passed — draft saved.',
    'wizard.gathering_data_auth': 'TRUSTED INFO',
    'wizard.draft_stored': 'Draft stored.',
    'wizard.delete_confirm': 'Are you sure?',
    'wizard.deleted_msg': 'Deleted.',

    // Wizard & Info Modals
    'wizard.info_title': 'Idea Notebook',
    'wizard.info_stolen': 'Creative Theft',
    'wizard.info_stolen_quote': '"A good artist doesn\'t copy, they steal." — Austin Kleon',
    'wizard.info_desc1': 'This is where your ideas take root. Note down everything that comes to mind, tag it, and save it.',
    'wizard.info_desc2': 'You can later blend your ideas in the Cabinet of Curiosities, and learn tactics to increase your creativity with the Kleon Playbook here.',
    'wizard.playbook': '✦ Kleon Playbook',
    'wizard.suggest_ai': 'Suggest AI',
    'wizard.summarize_ai': 'Summarize Idea',
    'wizard.note_name': 'NOTE NAME',
    'wizard.note_placeholder': 'Write your notes here...',
    'wizard.no_empty': 'Empty ideas cannot be saved.',
    'wizard.save_failed': 'Draft saved.',
    'wizard.save_success': '24 hours haven\'t passed — draft saved.',
    'wizard.bilgi': 'Info',
    'wizard.mikrofon_hata': 'Microphone could not be accessed.',
    'wizard.step_title_0': 'Idea',
    'wizard.step_title_1': '24h',
    'wizard.step_title_2': 'Doc',
    'wizard.step_title_3': 'S.W?',
    'wizard.step_title_4': 'Form',
    'wizard.step_title_5': 'Preview',
    'wizard.step_title_6': 'Control',
    'wizard.step_title_7': 'End',

    // Hub Info
    'hub.info_title': 'Own Your Domain',
    'hub.info_quote': '"Social networks are satellites. Your headquarters should be under your control." — Austin Kleon',
    'hub.info_desc1': 'This is where you gather your clan. Manage all your posts from here. You control your Social Graph here yourself.',
    'hub.info_desc2': 'You can track how much energy your shared posts consume (Vampire Test) and how much impact you create on which platforms from here.',

    // Cabinet Info
    'cabinet.info_title': 'Wunderkammern',
    'cabinet.info_quote': '"Your tastes are what make you you. Collecting feeds creating." — Austin Kleon',
    'cabinet.info_desc1': 'This is your museum. All your ideas are grouped here. Apply Austin Kleon\'s cabinet of curiosities philosophy here.',
    'cabinet.info_desc2': 'You can filter your ideas by their tags and see all the notes you wrote for a specific concept at once. If you reach 3 or 10 notes for a tag, you can blend the accumulated notes and turn them into guides (drafts) with one click!',

    // Templates
    'template.technical.label': 'Step-by-Step Technical Guide',
    'template.technical.headline': 'Aaron Franklin Style — Share Your Kitchen',
    'template.technical.body': 'Aaron Franklin publishes hours-long videos every year explaining barbecue techniques. Not just the result, but the fire build, meat selection, temperature control — every stage. The reader should be able to reach the same result by "watching" you.',
    'template.technical.quote': '"Showing people how it\'s done both enlightens them and connects them to you." — Austin Kleon',
    'template.technical.when': 'Use if these 6 contents are following steps.',

    'template.documentary.label': '"How I Made It?" Documentary',
    'template.documentary.headline': 'Show How the Sausage is Made',
    'template.documentary.body': 'People want to see "how the sausage is made." Share the kitchen, not just the result. Write the walls you hit, dead ends, "second act" difficulties — what Kleon calls "throwing rocks" moments — with an open heart. This makes you reliable.',
    'template.documentary.quote': '"Success stories inspire, but failure stories teach." — Austin Kleon',
    'template.documentary.when': 'Use if these contents represent mistakes and successes at different stages of a project.',

    'template.readingList.label': 'Inspiration and Attribution Booklet',
    'template.readingList.headline': 'Be an Open Node',
    'template.readingList.body': 'Kleon says sharing your resources makes you an "open node" — you are a junction point within the community. When you share the books, videos, and people that feed you, you are giving others a map for their own learning journeys.',
    'template.readingList.quote': '"Guide others, and they will follow you." — Austin Kleon, Show Your Work',
    'template.readingList.when': 'Use if these contents consist of resources you\'ve learned, documents you\'ve read, or ideas you\'ve caught from others.',

    'template.oldVsNew.label': '"Old vs. New" Development Template',
    'template.oldVsNew.headline': 'Journey from Amateur to Mastery',
    'template.oldVsNew.body': 'Comparing "What did I not know when I started this job, and what am I doing differently now?" gives the reader both humility and inspiration. Share your false beliefs, misconceptions, and corner turns. Amateurism is a starting point, not something to be ashamed of.',
    'template.oldVsNew.quote': '"Being an amateur is a privilege — you are someone whose curiosity hasn\'t been killed yet." — Austin Kleon',
    'template.oldVsNew.when': 'Use if these contents show your change over time — early period vs. current state.',

    // Guide Fields
    'guide.technical.tools.label': 'Tools, Libraries & Materials',
    'guide.technical.tools.hint': 'Like Aaron Franklin showing every tool one by one in his BBQ videos — the reader should be able to prepare with this list.',
    'guide.technical.tools.ph': 'E.g: VS Code, Node.js v20, Tailwind CSS, Railway.app — write each tool name and why you chose it.',
    
    'guide.technical.s1.label': 'Stage 1 — Preparation & Setup (Fire Build)',
    'guide.technical.s1.hint': 'Franklin first explains how to light the fire. You show how you started from scratch. What was installed, what was configured?',
    'guide.technical.s1.ph': 'What was the first step to start from scratch? Installation, configuration, creating the project skeleton...',
    
    'guide.technical.s2.label': 'Stage 2 — Main Work & Trade Secrets',
    'guide.technical.s2.hint': 'Start with "Normally nobody tells you this but...". Franklin shares temperature control tips in this part that are in no recipe book.',
    'guide.technical.s2.ph': 'How did the main work progress? What tips made a difference? What matches what others don\'t say?',
    
    'guide.technical.s3.label': 'Stage 3 — Results, Mistakes & Next Time',
    'guide.technical.s3.hint': 'Don\'t just say "it worked". Write what didn\'t work unexpectedly, what you fixed. This honesty builds trust.',
    'guide.technical.s3.ph': 'How did the result turn out? What mistakes were made? What would you change if you did the same job again?',
    
    'guide.documentary.target.label': 'Initial Goal & Intent',
    'guide.documentary.target.hint': 'Kleon says: "The fact that where you start and where you finish are different shows your honesty." What did you want to do?',
    'guide.documentary.target.ph': 'What did you imagine when starting this project/idea? What problem did you want to solve?',
    
    'guide.documentary.difficulties.label': 'Throwing Rocks — Second Act Challenges',
    'guide.documentary.difficulties.hint': '"Throwing rocks" = obstacles in the middle of the story. The protagonist (you) must overcome them. Write mistakes, dead ends, "it never worked" moments without shame.',
    'guide.documentary.difficulties.ph': 'Where did you stumble? Which of your assumptions turned out to be wrong? What didn\'t go as planned? How much time did you lose?',
    
    'guide.documentary.lessons.label': 'Lessons Learned & Solution',
    'guide.documentary.lessons.hint': 'A good documentary shows the hero\'s transformation. Start with "I learned by living this that...".',
    'guide.documentary.lessons.ph': 'What did you get in the end? How did this experience change you? What would you do next time?',
    
    'guide.readingList.sources.label': 'Books & Articles',
    'guide.readingList.sources.hint': '"Being an open node" = guiding others. Explain why each source is important with one sentence. Don\'t just make a list.',
    'guide.readingList.sources.ph': 'E.g:\n- "Show Your Work" — Kleon (broke the fear of sharing)\n- stripe.com/docs (best API documentation)\nGive a link, write why you recommend it.',
    
    'guide.readingList.multimedia.label': 'Videos, Podcasts & Courses',
    'guide.readingList.multimedia.hint': 'If someone is going to spend 30 minutes, why should they choose this content? Ask yourself: "What did this change for me?"',
    'guide.readingList.multimedia.ph': 'E.g:\n- Fireship YouTube (taught the concept in 10 minutes)\n- Syntax.fm Podcast — Ep.123 (found a solution to my deployment problem)',
    
    'guide.readingList.follows.label': 'Open Nodes — Who to Follow?',
    'guide.readingList.follows.hint': 'Kleon says: "Point to the people who feed you. This doesn\'t make you smaller, on the contrary, it adds you to their network." Explain why for each name.',
    'guide.readingList.follows.ph': 'E.g:\n- @kentcdodds — because he democratized test writing\n- Cassidy Williams — because she shows the power of "amateur" sharing',
    
    'guide.oldVsNew.oldWay.label': 'What Did I Know Before? What False Beliefs Did I Have?',
    'guide.oldVsNew.oldWay.hint': 'Kleon says: "Amateurism is a starting point, not something to be ashamed of." Sharing your old mistakes makes the reader say "I can do it too."',
    'guide.oldVsNew.oldWay.ph': 'When I started this job, I believed in these:\n- I couldn\'t start without understanding everything (wrong)\n- Code should be "perfect" (wrong)\n- I needed to be "ready" to share (wrong)',
    
    'guide.oldVsNew.newWay.label': 'What Am I Doing Differently Now? What Was My Breaking Moment?',
    'guide.oldVsNew.newWay.hint': 'Don\'t just say "I\'m better now". Exactly what changed, when did it turn? If there is a concrete "eureka" moment, tell it.',
    'guide.oldVsNew.newWay.ph': 'My breaking point was this:\n- When I solved an error message after 3 hours of effort...\nThings I do differently now:\n- I see mistakes as "teachers"\n- I share them in their raw state',

    // Auto-extracted components
    'Araçlar & Materyaller:': 'Tools & Materials:',
    'Aşama 1 — Hazırlık & Başlangıç:': 'Stage 1 — Prep & Start:',
    'Aşama 2 — Asıl İş & İpuçları:': 'Stage 2 — Main Work & Tips:',
    'Aşama 3 — Sonuç & Dersler:': 'Stage 3 — Results & Lessons:',
    'Başlangıç Hedefi:': 'Initial Goal:',
    'Throwing Rocks — Zorluklar:': 'Throwing Rocks — Challenges:',
    'Sürecin Öğrettikleri:': 'Lessons Learned:',
    'Kitaplar & Makaleler:': 'Books & Articles:',
    'Videolar & Podcastler:': 'Videos & Podcasts:',
    'Açık Düğümler — Takip Et:': 'Open Nodes — Follow:',
    'Eskiden (Yanlış İnançlar):': 'In the Past (False Beliefs):',
    'Şu An (Dönüşüm):': 'Now (Transformation):',
    'Merak Kabinesi': 'Cabinet of Curiosities',
    'Her eser bir müze objesidir. Kategorilere tıkla, serüvenin galerisini gör. Favori fikirlerini yıldızla.': 'Every work is a museum object. Click on categories, see the gallery of your adventure. Star your favorite ideas.',
    'Etiketler:': 'Tags:',
    'Temizle': 'Clear',
    'STOCK CONSOLIDATION': 'STOCK CONSOLIDATION',
    '— 10 esere ulaştın! Austin Kleon der ki: "Kendi sesini bulmanın yolu, başkalarının seslerini birleştirmekten geçer." Hemen bir rehber oluştur.': '— Reached 10 works! Austin Kleon says: "The way to find your own voice is to mix the voices of others." Create a guide now.',
    'Şablon Seç veya Sihirbazı Başlat': 'Select Template or Start Wizard',
    'Sihirbazla Devam Et': 'Continue with Wizard',
    'Sihirbazı Başlat': 'Start Wizard',
    'Bugün aklıma şu geldi...': 'Today I thought this...',
    'Etiketler': 'Tags',
    'yazılım,tasarım (virgülle ayır)': 'software,design (separate with comma)',
    'Yıldızla': 'Mark as favorite',
    'Bu fikir bugün ne anlam taşıyor?': 'What does this idea mean to you today?',
    'Kabineye Dön': 'Return to Cabinet',
    'Taslak': 'Draft',
    'Yayınlandı': 'Published',
    'Yayınlanmış': 'Published',
    'Tüm Eserleri Sil': 'Delete All Works',
    'ETİKETİ': 'TAG',
    'Uzman değilim, deneme yanılma yapıyorum.': 'I am not an expert, I am experimenting.',
    'Burada hiç fikir yok.': 'There are no ideas here.',
    'Bu kategoride henüz bir müze objesi yok.': 'There is no museum object in this category yet.',
    'Kayıp eserler aranıyor...': 'Searching for lost works...',
    'KAPAT': 'CLOSE',
    'Hemingway Taktiği': 'Hemingway Tactic',
    'Bu taslak yarım kalmış. Kaldığın yerden devam etmek için aşağıdaki butona bas — fikir Akış\'a yüklenecek.': 'This draft is incomplete. Press the button below to continue where you left off — the idea will be loaded to Flow.',
    'Bugün Devam Et': 'Continue Today',
    'MÜZE ESERLERİ': 'MUSEUM WORKS',
    'Görüntüle': 'View',
    'ATIF — İLHAM KAYNAĞI': 'ATTRIBUTION — INSPIRATION',
    'Yeniden Ziyaret Notu': 'Revisit Note',
    'Yayınla': 'Publish',
    'Dolduracağın Alanlar': 'Fields to Fill',
    'Başla — Soruları Cevapla': 'Start — Answer Questions',
    'Vazgeç': 'Cancel',
    'Her soruyu dürüstçe cevapla. Mükemmel olmasına gerek yok.': 'Answer every question honestly. It doesn\'t have to be perfect.',
    'Önizle →': 'Preview →',
    '← Geri': '← Back',
    'Rehber Önizleme': 'Guide Preview',
    '"İyi bir fikir asla tam bitmez, sadece yayınlanır." — Austin Kleon': '“A good idea is never completely finished, it just gets published.” — Austin Kleon',
    'Yayınla ✓': 'Publish ✓',
    '← Düzelt': '← Edit',
    'Stok Tamamlandı!': 'Stock Completed!',
    'etiketindeki eserlerini kalıcı bir değere dönüştürdün.': 'you transformed your works in the tag into a permanent value.',
    '"Küçük şeyler zamanla büyür. Bu rehber, birinin öğrenme yolculuğundaki bir kavşak noktası olacak." — Austin Kleon': '“Small things grow over time. This guide will be a crossroads in someone’s learning journey.” — Austin Kleon',
    'Stock Consolidation': 'Stock Consolidation',
    'ADIM 0 — Zaman Çizgisi + Seçim': 'STEP 0 — Timeline + Selection',
    'Birleştirmek istediğin fikirleri seç. Kleon felsefesi: "Noktaları birleştir, bütünü gör."': 'Select the ideas you want to combine. Kleon philosophy: "Connect the dots, see the whole."',
    'ADIM 1 — ÖRÜNTÜ BULUNDU': 'STEP 1 — PATTERN FOUND',
    'Aşağıdaki kelimeler seçtiğin fikirlerde en çok geçen örüntülerdir. Rehberinde vurgulamak istediklerini onayla.': 'The following words are the most common patterns in the ideas you selected. Confirm what you want to emphasize in your guide.',
    'SİSTEM ÖNERİSİ': 'SYSTEM RECOMMENDATION',
    'Bu fikirler ve onayladığın kelimeler en çok şu şablona uyuyor:': 'These ideas and the words you confirmed fit this template best:',
    'Kleon der ki: "Rehberin yapısı içindeki örüntüye göre şekillenir."': 'Kleon says: "The structure of the guide takes shape according to the pattern inside it."',
    'Onayladıklarımla Devam Et →': 'Continue with My Selections →',
    'ADIM 2 — Şablonu Kesinleştir': 'STEP 2 — Finalize Template',
    'Önerilen şablon en uygunu gibi görünüyor, ancak istersen başka bir tane seçebilirsin.': 'The recommended template seems to be the most suitable, but you can choose another one if you want.',
    'ÖNERİLEN': 'RECOMMENDED',
    'Seçili Şablonla Yazmaya Başla →': 'Start Writing with Selected Template →',
    'ADIM 3 — Rehberi Oluştur': 'STEP 3 — Create Guide',
    'Fikirlerini birleştirerek yeni bir değer üret. Yan taraftaki referansları kullanarak hızlanabilirsin.': 'Create a new value by combining your ideas. You can speed up by using the references on the side.',
    'Seçtiğin fikirlerden:': 'From your selected ideas:',
    'Önizleme ve Yayınla →': 'Preview and Publish →',
    'ADIM 4 — SON DOKUNUŞLAR': 'STEP 4 — FINAL TOUCHES',
    'Tamamlanmış Rehberin': 'Your Completed Guide',
    '← Düzenle': '← Edit',
    'Muazzam Stok Eritme!': 'Massive Stock Clearing!',
    'Seçtiğin fikirleri birleştirerek': 'By combining the ideas you selected',
    'üzerine harika bir rehber oluşturdun. Austin Kleon gurur duyardı!': 'you created a great guide on it. Austin Kleon would be proud!',
    'Araçlar & Malzemeler': 'Tools & Materials',
    'Aşama 1: Hazırlık': 'Stage 1: Prep',
    'Aşama 2: Uygulama': 'Stage 2: Execution',
    'Sonuç Tablosu': 'Results Table',
    'Hedef': 'Goal',
    'Karşılaştığım Zorluklar': 'Challenges I Faced',
    'Çıkardığım Dersler': 'Lessons I Learned',
    'Okuma Kaynakları': 'Reading Sources',
    'Ses ve Video': 'Audio and Video',
    'Sahiplenilecek Kişiler': 'People to Own',
    'Eskiden Böyle Düşünürdüm': 'I Used to Think So',
    'Artık Şunu Biliyorum': 'Now I Know This',
    'HEMINGWAY TAKTİĞİ': 'HEMINGWAY TACTIC',
    'Etiketlerde ara...': 'Search in Tags...',
    'TÜMÜ': 'ALL',
    'YILDIZLILAR': 'STARRED',
    'TASLAKLAR': 'DRAFTS',
    'ATIF': 'ATTRIBUTION',
    'Yayınlananlar': 'PUBLISHED',
    'ESER': 'WORK',
    'Fikir Defteri': 'Idea Notebook',
    'Örüntü (Pattern) Bulma': 'Finding Pattern',
    'Kleon der ki: "Bu içeriklere yukarıdan bak. Ortak nokta ne? Aynı dili mi kullanıyorlar, aynı hatayı mı çözüyorlar?"': 'Kleon says: "Look at these contents from above. What is the common point? Are they using the same language, solving the same mistake?"',
    'Görev:': 'Task:',
    'Bu rehberin ana fikrini, örüntüyü hissettirecek şekilde aşağıda güncelle.': 'Update the main idea of this guide below in a way that makes you feel the pattern.',
    'Bugünkü fikir veya gözlem': 'Today\'s idea or observation',
    'Devam Et': 'Continue',
    '24 Saat Testi': '24 Hour Test',
    'Bu fikri 24 saatten uzun süredir düşünüyor musun?': 'Have you been thinking about this idea for more than 24 hours?',
    'Evet, işleme al': 'Yes, process it',
    'Hayır, müzeye kaldır': 'No, send it to the museum',
    'Döküman & Artıklar': 'Document & Leftovers',
    'GÖRSEL': 'VISUAL',
    'SES': 'AUDIO',
    'YAZI': 'TEXT',
    'Ham malzeme': 'Raw material',
    'Amatör Modu': 'Amateur Mode',
    'Hata yapmaktan korkma. En ham halini paylaş.': 'Don\'t be afraid to make mistakes. Share the rawest version.',
    'Paylaşacağım →': 'I will share →',
    'Müzeye al': 'Send to museum',
    'So What? Testi': 'So What? Test',
    'Sturgeon Yasası:': 'Sturgeon\'s Law:',
    'Her şeyin %90\'ı çöptür. Neyin iyi neyin kötü olduğunu hemen bilemeyebilirsin.': '90% of everything is crap. You may not immediately know what is good and what is bad.',
    'Bir kıvılcım — devam': 'A spark — continue',
    'Emin değilim': 'I\'m not sure',
    'Sadece gürültü — sil': 'Just noise — delete',
    '← İptal': '← Cancel',
    'Rehber Bağlamı': 'Guide Context',
    'DVD Ekstrası gibi düşün:': 'Think like a DVD Extra:',
    'Bunlar sınav soruları değil. İki cümle yeter — Kleon der ki "dünyanın senden istediği şey sadece kısa bir açıklamadır."': 'These are not exam questions. Two sentences are enough — Kleon says "what the world wants from you is just a brief explanation."',
    'Hikaye': 'Story',
    '— geçmiş · şimdi · gelecek': '— past · present · future',
    'Özetleniyor...': 'Summarizing...',
    'Kaydı Bitir': 'End Recording',
    'Sesli Anlat (AI Özetlesin)': 'Tell with voice (Let AI summarize)',
    'Müze Etiketi': 'Museum Tag',
    '(isteğe bağlı)': '(optional)',
    '✓ link var': '✓ has link',
    'İsim verdin ama link yok — Kleon\'a göre linksiz atıf internette neredeyse görünmez.': 'You gave a name but no link — according to Kleon, attribution without a link is almost invisible on the internet.',
    'Henüz uzman değilim, deneme yanılma yapıyorum': 'I\'m not an expert yet, I\'m doing trial and error',
    'Harmanla →': 'Blend →',
    'Önizleme →': 'Preview →',
    'DÜZENLENEBİLİR': 'EDITABLE',
    'SÜSLE': 'DECORATE',
    'Kleon der ki:': 'Kleon says:',
    '"İyi bir fikir asla tam bitmez, sadece yayınlanır." Hatalarıyla kucakla. Bu senin': '"A good idea is never completely finished, it just gets published." Embrace it with its flaws. This is your',
    'stoğun': 'stock',
    'Yayın Platformu': 'Publishing Platform',
    'Kendi Web Sitem — Karargah': 'My Website — HQ',
    'X (Twitter) — Uydu': 'X (Twitter) — Satellite',
    'LinkedIn — Profesyonel Uydu': 'LinkedIn — Professional Satellite',
    'Substack — Bülten Köşesi': 'Substack — Newsletter Corner',
    'Vampir Testi': 'Vampire Test',
    'Veri toplanıyor...': 'Collecting data...',
    'VAMPİR UYARISI': 'VAMPIRE WARNING',
    'Metriklerin kölesi olduklarında yaratıcılıkları öldü.': 'Their creativity died when they became slaves to metrics.',
    'Mükemmeliyetçilik Bir Hapishanedir:': 'Perfectionism is a Prison:',
    'Öleceksin. Bu yüzden bu kusurlu haliyle yayınla. Gerçek başarı sürekliliktedir.': 'You will die. So publish it in its flawed state. True success is in continuity.',
    'Gözünü kapat ve yayınla': 'Close your eyes and publish',
    'Kalıcı Bir Değer Yarattın': 'You Created a Permanent Value',
    '"Fikirlerinizi stoklayın. Onları biriktirin, düzenleyin ve başkalarına fayda sağlayacak bir bütüne dönüştürün."': '"Stock your ideas. Collect them, organize them, and turn them into a whole that will benefit others."',
    '— Austin Kleon, Show Your Work': '— Austin Kleon, Show Your Work',
    'Bugün bir iz bıraktın.': 'You left a mark today.',
    'Austin Kleon: "Başkalarının işlerini çalın, kendi stilinizi harmanlayın."': 'Austin Kleon: "Steal other people\'s work, blend your own style."',
    'Sabbatical Başladı:': 'Sabbatical Started:',
    'Cihazları kapat. Bir ağaca bak. Köpeğini gezdir.': 'Turn off the devices. Look at a tree. Walk your dog.',
    'Hemingway Taktiği — yarın kaldığın yerden devam et:': 'Hemingway Tactic — continue where you left off tomorrow:',
    'Kaydet & Sabbatical\'a çık': 'Save & Go on Sabbatical',
    'Geri Dön': 'Go Back',

    'cabinet.delete_confirm': 'Are you sure you want to delete {label}?',
    'Emin misiniz?': 'Are you sure?',
    'En az 2 fikir seç': 'Select at least 2 ideas',
    'Fikri Birleştir →': 'Combine Ideas →',
    'Seçtiğin {count} fikir arasındaki ortak noktalar:': 'Common points among the {count} ideas you chose:',
    'tour.skip': 'Skip',
    'tour.prev': 'Back',
    'tour.next': 'Continue',
    'tour.finish': 'Start ✦',
    'tour.step1.title': '1. Intro: Idea Notebook',
    'tour.step1.phil': 'Philosophy',
    'tour.step1.quote': '"Austin Kleon says: You don\'t have to be a genius. Creativity is placing yourself within a \'scenius\'."',
    'tour.step1.desc': 'Write down even your smallest observation here. Amateurs aren\'t afraid to try because they have nothing to lose.',
    'tour.step2.title': '2. Tags: Group Them',
    'tour.step2.desc': 'Ideas with the same tag accumulate over time to form a <strong>Stock</strong>. Austin Kleon\'s advice: Find commonalities and combine them.',
    'tour.step2.hint': 'You can proceed by clicking the Continue button.',
    'tour.step3.title': '3. 24-Hour Test',
    'tour.step3.phil': 'Austin Kleon',
    'tour.step3.quote': '"Sharing everything instantly can lead to human spam."',
    'tour.step3.desc': 'Keep the idea for 24 hours. If it still excites you, process it; otherwise, <strong>Send to Museum</strong>.',
    'tour.step3.ways': 'There are two ways:',
    'tour.step3.way1': '✅ <strong>Yes, process it</strong> → Moves to Document step',
    'tour.step3.way2': '🏛️ <strong>Send to Museum</strong> → Draft is saved, tour ends',
    'tour.step4.title': '4. Document & Leftovers',
    'tour.step4.phil': 'Share the Process',
    'tour.step4.quote': '"Show how the sausage is made. Residue is as valuable as the product itself."',
    'tour.step4.desc': 'Add visuals, record audio, or keep text notes.',
    'tour.step4.way1': '📤 <strong>I will share →</strong> Moves to So What? test',
    'tour.step4.way2': '🏛️ <strong>Send to Museum</strong> → Draft is saved, tour ends',
    'tour.step5.title': '5. Raw Material',
    'tour.step5.desc': 'Pour your code snippets, sketches, or raw notes here. According to Austin Kleon, <em>"Sharing the raw version is honesty."</em>',
    'tour.step6.title': '6. So What? Test',
    'tour.step6.phil': 'Generosity',
    'tour.step6.quote': '"Sharing is an act of generosity, not ego satisfaction."',
    'tour.step6.desc': 'Ask yourself: Is this useful for someone else?',
    'tour.step6.ways': 'There are three ways:',
    'tour.step6.way1': '✨ <strong>A spark — continue</strong> → Moves to Story step',
    'tour.step6.way2': '🏛️ <strong>I\'m not sure</strong> → Draft is saved',
    'tour.step6.way3': '🗑️ <strong>Just noise — delete</strong> → Idea is deleted',
    'tour.step7.title': '7. Story & Context',
    'tour.step7.phil': 'Austin Kleon',
    'tour.step7.quote': '"The work doesn\'t speak for itself. People want to know the story."',
    'tour.step7.desc': 'What did you aim for in the past, where are you now? Two sentences are enough — write your story here.',
    'tour.step8.title': '8. Attribution Etiquette',
    'tour.step8.phil': 'Honesty',
    'tour.step8.quote': '"Attribution is the main currency of the Internet. Attribution without a link is almost invisible."',
    'tour.step8.desc': 'Specify the person and source you were inspired by. Then press the <strong>Blend →</strong> button.',
    'tour.step9.title': '9. Blended Story',
    'tour.step9.phil': 'Final Touch',
    'tour.step9.quote': '"A good idea is never completely finished, it just gets published." — Kleon',
    'tour.step9.desc': 'You can edit the text from the area below or enrich it with the ✨ <strong>Decorate AI</strong> button. Then press the <strong>Continue →</strong> button.',
    'tour.step10.title': '10. Vampire Test',
    'tour.step10.phil': 'Energy Control — Austin Kleon',
    'tour.step10.quote': '"The vampire test is simple: If something makes you feel energetic, continue. If it consumes you, leave it."',
    'tour.step10.desc1': 'According to Kleon, perfectionism is the biggest vampire. Number of likes, retweet expectation — these kill your creativity.',
    'tour.step10.desc2': 'Check if your idea feeds you. If you\'re ready, press the <strong>"Close your eyes and publish"</strong> button!',
    'tour.step11.title': '11. Publish',
    'tour.step11.desc': 'Close your eyes and publish. Real success is in continuity and the courage to share in its raw state.',
    'tour.step11.hint': 'Click the button and publish!',
    'tour.step12.title': '12. Hemingway Technique',
    'tour.step12.phil': 'Continuity',
    'tour.step12.quote': '"Hemingway would stop writing when he knew where he was going the next day."',
    'tour.step12.desc': 'Write where you will start tomorrow. This method eliminates <em>writer\'s block</em>.',
    'tour.step13.title': '13. Cabinet of Curiosities',
    'tour.step13.phil': 'Wunderkammern',
    'tour.step13.quote': '"Your tastes are what make you you. Collecting feeds creating."',
    'tour.step13.desc': 'This is your museum. All your ideas are grouped here.',
    'tour.step14.title': '14. Tag Filters',
    'tour.step14.desc': 'You can filter your ideas by their tags and see all the notes you wrote for a specific concept at once.',
    'tour.step15.title': '15. Stock Accumulated Alerts',
    'tour.step15.desc': 'If you reach 3 or 10 notes for a tag, an exclamation mark appears on the tag. As Austin Kleon said: "Accumulate your ideas." You can blend the accumulated notes and turn them into guides (drafts) with one click!',
    'tour.step16.title': '16. Selection',
    'tour.step16.desc': 'Select the ideas you want to combine. Connecting the dots and seeing the whole is the first step.',
    'tour.step17.title': '17. Pattern',
    'tour.step17.desc': 'You examine the most common words in the ideas you select. Confirm what you want to emphasize in your guide.',
    'tour.step18.title': '18. Finalize Template',
    'tour.step18.desc': 'The system automatically suggests the template (Technical Guide, Documentary, etc.) most suitable for the found pattern. You can change it if you want.',
    'tour.step19.title': '19. Template: Step-by-Step Guide',
    'tour.step19.desc': 'Austin Kleon says: "When you learn, teach others too." Choose this template to explain how you understood a subject in simple steps without looking down on anyone.',
    'tour.step20.title': '20. Template: Documentary',
    'tour.step20.desc': '"Share the process, not the final product." Use this template to convey the difficulties you encountered, your breaking moments, and the results you reached in story format.',
    'tour.step21.title': '21. Template: Attribution Booklet',
    'tour.step21.desc': '"You are a mix of what you read." It is for respectfully compiling and presenting the resources you were influenced by, from whom you stole (quoted) which ideas.',
    'tour.step22.title': '22. Template: Old vs. New',
    'tour.step22.desc': 'It is for showing with sharp transitions how your old beliefs were destroyed and how they were replaced by (contrasts) with what you newly learned.',
    'tour.step23.title': '23. Create the Guide',
    'tour.step23.phil': 'Blend Thoughts',
    'tour.step23.quote': '"Connect the dots, see the whole." — Austin Kleon',
    'tour.step23.desc': 'Write a new and big guide by referencing your old ideas. Answer the relevant questions listed in the boxes below with your own words.',
    'tour.step23.hint': 'You can instantly add your notes to the box by clicking the <strong>"From your selected ideas"</strong> buttons at the bottom, then combine them with your own sentences.',
    'tour.step24.title': '24. Final Touch and Publication',
    'tour.step24.desc': 'Review your work and publish it on the Hub if you want. You\'ve cleared your stocks as Austin Kleon recommended!',
    'tour.step25.title': '25. World HQ',
    'tour.step25.phil': 'Own Your Domain',
    'tour.step25.quote': '"Social networks are satellites. Your headquarters should be under your control."',
    'tour.step25.desc': 'This is where you gather your clan. Manage all your posts from here.',
  }
};

export const LanguageProvider: React.FC<{ children: React.ReactNode }> = ({ children }) => {
  const [lang, setLang] = useState<Language>(() => {
    return (localStorage.getItem('app_language') as Language) || 'tr';
  });

  useEffect(() => {
    localStorage.setItem('app_language', lang);
  }, [lang]);

  const t = (key: string, args?: Record<string, string | number>): string => {
    let result = translations[lang][key] || key;
    if (args) {
      Object.keys(args).forEach(k => {
        result = result.replace(new RegExp(`{${k}}`, 'g'), String(args[k]));
      });
    }
    return result;
  };

  return (
    <LanguageContext.Provider value={{ lang, setLang, t }}>
      {children}
    </LanguageContext.Provider>
  );
};

export const useLanguage = () => {
  const context = useContext(LanguageContext);
  if (!context) {
    throw new Error('useLanguage must be used within a LanguageProvider');
  }
  return context;
};
